name: Build FaceApp Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clean build cache
        run: |
          # Remove buildozer's internal cache and the output 'bin' directory
          # Buildozer usually places APKs in 'bin/' at the root when run from root.
          rm -rf .buildozer
          rm -rf bin # Corrected path for cleaning the output directory
      - name: Build APK
        # This action runs buildozer. The 'workdir: .' means buildozer runs
        # in the root of your repository, so the APK will be in 'bin/'.
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          workdir: .
          buildozer_version: stable
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: faceapp-integrated-apk
          # Corrected path: APKs are typically generated in the 'bin/' directory
          # at the root level wh
